### ISSUE TITLE
Working with error messages

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/validation#11]
Laravel Message Bag is an elaborate key/value storage system for storing different types of messages. Right now,  we're using the session for storing messages.
```python
errors = request.validate(
    validate.required('phone'),
    validate.length('phone', min=6, max=10)
)
if errors:
    return request.back().with_errors(errors)
```
You'll have something like this as error in the session:
```
{'phone': ['phone is required', 'phone length must be between 3 and 999999']}
```
How can I display the first error message for a given field? Laravel provides `first` method, and others useful [methods](https://stillat.com/blog/2016/11/29/an-introduction-to-laravel-message-bags).

**Comment by josephmancuso** [comment]
https://github.com/MasoniteFramework/validation/pull/12
