### ISSUE TITLE
Nested JSON with List Validation has weird behaviour

### ISSUE THREAD

**Issue by mistletoedev** [MasoniteFramework/validation#25]
Hi, Today i encounter weird behaviour of Nested JSON with List in it. 

Following is part of validation code:
`request.validate(
            validator.required(['name', discounts_ref']),
            validator.numeric(['discounts_ref.*']),
)`

I tested that code with three payload:
First: (works as expected) raise ValueError
`{
   "name":"PRD-1"
}`

Second: (Weird behaviour) raise ValueError for required, and numeric, expected output should be only "required rule" which should be validated.
`{
   "name":"PRD-1",
   "discounts_ref":[],
}`

Third: (Weird behaviour) raise list index out of range, and should be not raising any error.
`{
   "name":"PRD-1",
   "discounts_ref":[
			2, 3
   ],
}`

Other rule involving nested list also broken, such as `validator.length`, i have not test all rule with my test case.

Using Masonite Package masonite>=2.2,<2.3.

**Comment by josephmancuso** [comment]
@mistletoedev I didn't see this before ... Just worked on it now and this is fixed in version 3.0.6
