### ISSUE TITLE
Validate files

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/validation#27]
```
validate.file('photo'),
validate.image('photo'),
validate.mimes('photo', 'jpeg,png,gif,webp'),
validate.max_size(2048),
```
Just some random ideas about files validation.

**Comment by girardinsamuel** [comment]
I am working on it ;) !

For now I tried to add multiple parameters to the `file` validation rule.
Then we could add other validation rules such as `image` or `document` or `video` based on previous validation rules.

More info in #36 .

**Comment by girardinsamuel** [comment]
@nioperas06 I have completed this feature 💪, hope it fits into what you had in mind ! See here #36
