### ISSUE TITLE
Tests of date rule are obsolete

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/validation#32]
The tests are implemented with a hard-coded future date which has been reached.

Maybe use a dynamic date to fix that ! I'll open a PR.

**Comment by girardinsamuel** [comment]
Actually dynamic dates are used but one block in the test uses a hardcoded string. What is the goal here ? Should we delete the first block ?
```python
        validate = Validator().validate({
            'date': '2020-05-21T22:00:00',
        }, is_future(['date']))

        self.assertEqual(len(validate), 0)

        validate = Validator().validate({
            'date': pendulum.tomorrow().to_datetime_string(),
        }, is_future(['date'], tz='America/New_York'))

        self.assertEqual(len(validate), 0)
```

**Comment by josephmancuso** [comment]
Yes remove the first one and use pendulum to make them dynamic
