### ISSUE TITLE
Fix code formatting

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/validation#34]
Now that flake8 and black "configuration/command" are added to the repo, we could format the code according to this rules (so that Github lint job succeed).

**Comment by josephmancuso** [comment]
Just know that Masonite 2.3 needs to run on Python 3.5+. All Masonite packages for Masonite 2.3 need to also obviously run for Python 3.5+. With that being said, black requires Python 3.6+ so if we add it to the requirements.txt then the GitHub actions will break. Best bet is to run black locally for now and then commit the formatting as a commit or a PR

**Comment by josephmancuso** [comment]
Theres actually a few Masonite repo's that are outdated and using circleci still but they really should be using GitHub actions and makefiles. especially for deployments. If you want to go through the active ones and either add issues there or open PR's with the same stuff you did in one of the last PR's that would be great

**Comment by girardinsamuel** [comment]
I fixed linting of this repo in the PR #35

**Comment by girardinsamuel** [comment]
I close this issue then as PR is merged
