### ISSUE TITLE
Inconsistency between exists and required validation rule

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/validation#45]
I have found that both rules are checking that the key is present in the dict under validation.

My opinion is that :
* those two rules must be different (otherwise no need for two rules named differently)
* `required`: value must be there and not null (null here can be considered with truthy meaning)
* `exists`: value must exists in the dictionary (but can be null)

If you agree with that I'll open a PR to update that, but that's a breaking change I guess.

**Comment by Marlysson** [comment]
Plus to this quote:

> required: value must be there and not null (null here can be considered with truthy meaning)

I'm trying some tests here and when validate against `required` rule, even if input are in request, it can be empty like that:

```json
{"name" : ""}
```

Then the `required` rule should not passes, but actually it pass as correct.

**Comment by girardinsamuel** [comment]
@Marlysson Yes indeed, thanks for reporting this.

I fixed this in PR #44, we will merge for Masonite 3.0 I guess 😉 .

**Comment by josephmancuso** [comment]
Fixed in #44
