### ISSUE TITLE
add nullable validation rule

### ISSUE THREAD

**Issue by girardinsamuel** [MasoniteFramework/validation#53]
The `nullable` validation rule would if present in the list of rules for this field always passes if the field is null/empty.
I finds this feature very useful and right now I missed it: I need to write some complex workarounds to achieve what I want to do.

Example of what I would like to write : 
```python
errors = request.validate({
  'username': 'required',
  'nickname': 'nullable|length:3..15'  # if nickname is empty length rule will not complain
  'avatar': 'nullable|image', # if avatar is empty, image rule will not complain
})
```

right now I can't use the string validation format AND I need to write stuff like this:
```python
 errors = self.request.validate(
            validate.required(["username"]),
            validate.when(validate.isnt(validate.none("nickname"))).then(
                validate.length("nickname", min=3, max=15)
            ),
            validate.when(validate.isnt(validate.none("avatar"))).then(
                validate.image("avatar")
            ),
        )
```

**Comment by girardinsamuel** [comment]
Laravel has such a validation rule and is explained here:
https://laravel.com/docs/8.x/validation#a-note-on-optional-fields

I am feeling we need to add this, I don't how to achieved this quickly and nicely with the current rules ?

**Comment by tpow** [comment]
I wonder if adding a "none_allowed" or "null_allowed" boolean to length (and others where relevant, such as image) would be an easier and clearer alternative?

As an aside, I liked the idea of TrimStrings middleware mentioned in the Laravel link, but suspect that the ConvertEmptyStringsToNull middleware could be more painful than helpful.

**Comment by girardinsamuel** [comment]
@tpow 
> I wonder if adding a "none_allowed" or "null_allowed" boolean to length (and others where relevant, such as image) would be an easier and clearer alternative?

That's exactly what I am proposing 😉 , was thinking of naming it "nullable", but then the implementation could be different depending on validation format (string or classical):

With classical validation, I guess that's what you propose:
```python
 errors = self.request.validate(
            validate.required(["username"]),
            validate.length("nickname", min=3, max=15, nullable=True),
            validate.image("avatar", nullable=True)
        )
```
With string validation I find Laravel style really cool (but this one is harder to implement).
```
errors = request.validate({
  'username': 'required',
  'nickname': 'nullable|length:3..15'
  'avatar': 'nullable|image', 
})
```

So we might add the first one and later on the second one eventually !

**Comment by tpow** [comment]
Yes, I was thinking like your first example with "nullable" (or whatever it's called) as a keyword argument to the different functions. If I'm not mistaken, with the string validation format, different function calls are separated by the vertical bar (|). This would be equivalent to validate.nullable("nickname"), I think.

**Comment by girardinsamuel** [comment]
yes actually in my previous comment the two snippets are equivalent !

**Comment by girardinsamuel** [comment]
@josephmancuso @Marlysson what's your thoughts about this ?

**Comment by girardinsamuel** [comment]
I am closing this issue, as if implemented it will be done into Masonite core.
