### ISSUE TITLE
`isnt` validation rule

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/validation#7]
This is the different rule among the available rules.
```python
validate.isnt(
  validate.is_in('age', [2,4,5])
)
```
I think we should create something like the other rules: `validate.isnt('age', [2,4,5])`. And by the way, why not call it `not_in`?

**Comment by josephmancuso** [comment]
Isn’t is used for negation. It could also be isnt(required(..))

**Comment by nioperas06** [comment]
Damn 🤦‍♂ , got it!

**Comment by josephmancuso** [comment]
wait there is no `not_in` validation rule

**Comment by josephmancuso** [comment]
we need that lol
