### ISSUE TITLE
`unique` validation rule or something not exist within the given database table.

### ISSUE THREAD

**Issue by nioperas06** [MasoniteFramework/validation#8]
Currently, I'm doing something like this:
```python
...
validate.isnt(
    validate.is_in('email', User.all().pluck('email'))
),
...
```
And I'm getting this as error: `email must not contain an element in <orator.orm.collection.Collection object at 0x10fd37898>
 `. So basically, I need to provide an array 🤔

**Comment by josephmancuso** [comment]
what do you mean? are you saying its working or not working? lol

**Comment by nioperas06** [comment]
lol It's working. just point out that the default message is `email must not contain an element in <orator.orm.collection.Collection object at 0x10fd37898>`

**Comment by josephmancuso** [comment]
oh i see, well its a collection because you gave it a collection object

**Comment by josephmancuso** [comment]
you can change the message thoughh if you want

**Comment by nioperas06** [comment]
Better for UX, lol

**Comment by josephmancuso** [comment]
yeah deff

**Comment by josephmancuso** [comment]
looking at this again, if we did something like deserialized the collection into an array, it would list all your user's emails.
